apiVersion: v1
kind: Service
metadata:
  name: {{ include "m1-postgres.fullname" . }}
  labels:
    {{- include "m1-postgres.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: 
    {{- include "m1-postgres.selectorLabels" . | nindent 4 }}
