apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nifi
  namespace: argocd
spec:
  project: default
  source:
    chart: nifi
    repoURL: https://cetic.github.io/helm-charts
    targetRevision: 1.1.0
    helm:
      releaseName: nifi
      values: |
        # Number of nifi nodes
        replicaCount: 1

          ## Set default image, imageTag, and imagePullPolicy.
          ## ref: https://hub.docker.com/r/apache/nifi/
          ##
        image:
          repository: apache/nifi
          tag: "1.14.0"
          pullPolicy: "IfNotPresent"
        ingress:
          enabled: true
          # className: nginx
          annotations: {}
          tls: []
          hosts: localhose
          path: /
          # If you want to change the default path, see this issue https://github.com/cetic/helm-nifi/issues/22
        zookeeper:
          ## If true, install the Zookeeper chart
          ## ref: https://github.com/bitnami/charts/blob/master/bitnami/zookeeper/values.yaml
          enabled: false
        # Configure metrics
        metrics:
          prometheus:
            # Enable Prometheus metrics
            enabled: true
            # Port used to expose Prometheus metrics
            port: 9092
            serviceMonitor:
              # Enable deployment of Prometheus Operator ServiceMonitor resource
              enabled: false
              # namespace: monitoring
              # Additional labels for the ServiceMonitor
              labels: {}

  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
