apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: database
  namespace: airflow
spec:
  project: default
  source:
    chart: postgresql
    repoURL: https://thenextceo.github.io/postgresql/
    targetRevision: 1.0.0
    helm:
      releaseName:
        database
        # Values file as block file

  destination:
    server: "https://kubernetes.default.svc"
    namespace: airflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
