apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: database
  namespace: airflow
spec:
  project: default
  source:
    chart: postgresql
    repoURL: https://thenextceo.github.io/postgresql/
    targetRevision: 0.0.1
