apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: database
  namespace: argocd
spec:
  project: default
  source:
    chart: postgresql
    repoURL: https://thenextceo.github.io/postgresql
    targetRevision: 0.0.1
    helm:
      values: |
        replicaCount: 1
        image:
          repository: postgres
          pullPolicy: IfNotPresent
          tag: "13.5-bullseye"

        imagePullSecrets: []
        nameOverride: ""
        fullnameOverride: ""

        serviceAccount:
          create: false
          annotations: {}
          name: ""

        containerPort: 5432

        podAnnotations: {}

        podSecurityContext:
          {}

        securityContext:
          {}

        service:
          type: ClusterIP
          port: 5432

        ingress:
          enabled: false
          className: ""
          annotations:
            {}
          hosts:
            - host: localhost
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls: []
          #  - secretName: chart-example-tls
          #    hosts:
          #      - chart-example.local

        connection:
          database: postgres
          username: username
          password: password
          
        resources:
          {}

        autoscaling:
          enabled: false
          minReplicas: 1
          maxReplicas: 100
          targetCPUUtilizationPercentage: 80
          # targetMemoryUtilizationPercentage: 80


  destination:
    name: ""
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
